import type {
  BatchRecord,
  PayoutItemRecord,
  ValidationRuleViewModel,
} from '../types'
import { maskAddress } from '../utils/tron'

const now = new Date().toISOString()

export const sampleBatches: BatchRecord[] = [
  {
    id: 'batch-001',
    name: 'April Partner Disbursement',
    sourceFileName: 'partner-payouts-apr.xlsx',
    lifecycle: 'Validated',
    status: 'Awaiting execution',
    network: 'TRON Mainnet',
    senderAddress: 'TXYQJ8sMfjP4P91hUj8hYFQxwVm6mKxD7c',
    tokenSymbol: 'USDT',
    tokenContract: 'TXLAQ63Xg1NAzckPwKHvzw7CSEmLMEqcdj',
    totalCount: 500,
    validCount: 492,
    invalidCount: 8,
    successCount: 0,
    failedCount: 0,
    totalAmount: '18524.440000',
    estimatedEnergy: 1625000,
    estimatedBandwidth: 25000,
    concurrency: 8,
    startedAt: null,
    completedAt: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'batch-002',
    name: 'Referral Rewards Wave 7',
    sourceFileName: 'referrals-wave-7.csv',
    lifecycle: 'Paying',
    status: 'Broadcasting',
    network: 'TRON Mainnet',
    senderAddress: 'TXYQJ8sMfjP4P91hUj8hYFQxwVm6mKxD7c',
    tokenSymbol: 'USDT',
    tokenContract: 'TXLAQ63Xg1NAzckPwKHvzw7CSEmLMEqcdj',
    totalCount: 220,
    validCount: 220,
    invalidCount: 0,
    successCount: 149,
    failedCount: 4,
    totalAmount: '9270.000000',
    estimatedEnergy: 715000,
    estimatedBandwidth: 11000,
    concurrency: 6,
    startedAt: now,
    completedAt: null,
    createdAt: now,
    updatedAt: now,
  },
]

export const samplePayoutItems: PayoutItemRecord[] = [
  {
    id: 'item-001',
    batchId: 'batch-002',
    lineNumber: 12,
    recipient: 'TGzz8gjYiYRqpfmDwnLxfgPuLVNmpCswVp',
    maskedRecipient: maskAddress('TGzz8gjYiYRqpfmDwnLxfgPuLVNmpCswVp'),
    amount: '25.500000',
    reference: 'REF-12',
    status: 'Success',
    errorCode: null,
    errorMessage: null,
    txId: 'd4b0bc76a2f2472190d8ffac0bdb1a91f7a2f64795ebd4f5c9126b728f1e2a12',
    explorerUrl:
      'https://tronscan.org/#/transaction/d4b0bc76a2f2472190d8ffac0bdb1a91f7a2f64795ebd4f5c9126b728f1e2a12',
    idempotencyKey: '3dbf0e64-a171-4acd-ae4c-49f8cfef2ced',
    attemptCount: 1,
    signedAt: now,
    broadcastAt: now,
    confirmedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'item-002',
    batchId: 'batch-002',
    lineNumber: 13,
    recipient: 'TJQeZT6kqAuTL9QxK5rRrQqvGjufH6G6wK',
    maskedRecipient: maskAddress('TJQeZT6kqAuTL9QxK5rRrQqvGjufH6G6wK'),
    amount: '120.000000',
    reference: 'REF-13',
    status: 'Confirming',
    errorCode: null,
    errorMessage: null,
    txId: 'c32d3a4d0ea4ca39910f437a59e0d4c21ef0f3254d04f88ec876f9c53fb04f21',
    explorerUrl:
      'https://tronscan.org/#/transaction/c32d3a4d0ea4ca39910f437a59e0d4c21ef0f3254d04f88ec876f9c53fb04f21',
    idempotencyKey: '3bd2cf6f-fd16-4fd9-90e4-6643f813ce72',
    attemptCount: 1,
    signedAt: now,
    broadcastAt: now,
    confirmedAt: null,
    createdAt: now,
    updatedAt: now,
  },
]

export const sampleValidationRules: ValidationRuleViewModel[] = [
  {
    label: 'Base58Check addresses',
    description: 'Reject malformed TRON recipients before transaction build.',
    state: 'Validated',
  },
  {
    label: 'USDT precision',
    description: 'Block values above 6 decimal places and non-positive rows.',
    state: 'Validated',
  },
  {
    label: 'Duplicate detection',
    description: 'Catch repeated recipient + amount + reference combinations.',
    state: 'Validated',
  },
  {
    label: 'Budget control',
    description: 'Fail validation when spend exceeds available USDT balance.',
    state: 'Validated',
  },
]